deps:
	go mod tidy
	go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest

win:
	set GOOS=windows
	set GOARCH=amd64
	goversioninfo
	cd
	go  build -ldflags "-s -w -H windowsgui" -o ./bin/3-Min-Sleep.exe
	del resource.syso